#THEORITICAL QUESTIONS

##1  Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

In [3]:
#Purpose of NumPy in Scientific Computing and Data Analysis
#NumPy (Numerical Python) is a powerful library in Python that provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. It is widely used in scientific computing and data analysis due to its efficiency in handling and processing numerical data.

In [5]:
#Advantages of NumPy

#Efficient Memory Usage-	NumPy arrays are more compact and memory-efficient compared to Python lists because they store data in a continuous block of memory.
#Faster Computations-	Operations on NumPy arrays are highly optimized using C and Fortran, making numerical computations much faster than using pure Python.
#Vectorized Operations-	NumPy allows element-wise operations on arrays without explicit loops, reducing the code complexity and speeding up performance.
#Support for Large Arrays-	It efficiently handles large datasets and operations that involve matrices or multi-dimensional arrays (e.g., n-dimensional arrays).
#Wide Range of Functions-	Includes numerous built-in mathematical functions (e.g., trigonometric, statistical, linear algebra), making it easy to perform complex computations.
#Interoperability-	Compatible with other Python libraries like Pandas, Matplotlib, and SciPy, allowing seamless integration for data manipulation and visualization.
#Broadcasting-	Automatically expands arrays of smaller dimensions to match larger ones in operations, making code shorter and easier to read.
#Indexing and Slicing-	Offers powerful tools for indexing and slicing arrays, making it easier to select and manipulate data at various levels of granularity.

In [8]:
#How NumPy Enhances Python's Numerical Capabilities

#Array Handling-	Python lists are versatile but inefficient for numerical computations. NumPy provides fast, homogeneous n-dimensional arrays that significantly outperform lists in numerical tasks.
#Mathematical Functions-	Python’s standard library lacks specialized numerical operations. NumPy enriches Python with efficient routines for linear algebra, Fourier transforms, random number generation, and statistical operations.
#Broadcasting-	Python lacks efficient array-wise broadcasting. NumPy’s broadcasting mechanism allows operations between arrays of different shapes, facilitating more concise code.
#Integration with C/Fortran-	NumPy is built on top of C, allowing Python to leverage low-level performance optimizations, giving Python near C-like speed for numerical operations.


##2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the 
other?

In [11]:
#Differences
#Weights Support:

#np.mean() is used for simple averaging, where all elements contribute equally.
#np.average() allows for a weighted average, which is useful when some elements are more important than others.
#Flexibility:

#np.mean() is simpler and ideal for general use.
#np.average() provides greater flexibility through the weights parameter but requires the user to input weights if applicable.
#Behavior without Weights:

#Without weights, np.average() behaves exactly like np.mean(). However, np.mean() is the more straightforward option when weights aren’t needed.

In [ ]:
#When to Use Each Function

#You want to calculate the simple arithmetic mean of an array without considering weights.-	np.mean()
#You need to calculate an average where certain values should contribute more heavily (e.g., grades weighted by credits).-	np.average()
#You have no need for weighted calculations and want a more concise, straightforward function.-	np.mean()
#You are working with datasets where different elements have different levels of significance or importance.-	np.average()


In [15]:
#np.mean() Example:
import numpy as np
arr = np.array([1, 2, 3, 4])
mean = np.mean(arr)  


In [17]:
#np.average() Example with Weights:
import numpy as np
arr = np.array([1, 2, 3, 4])
weights = np.array([1, 2, 3, 4])
weighted_avg = np.average(arr, weights=weights) 

##3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D 
arrays.

In [20]:
#Methods for Reversing a NumPy Array

#Array Slicing ([::-1])	-The most common way to reverse an array in NumPy is by slicing with [::-1], which works for any axis.	
#np.flip()-  Reverses the order of elements along a specified axis. For multidimensional arrays, you can specify the axis.	
#np.flipud() and np.fliplr()-	np.flipud() flips an array upside down (along rows), and np.fliplr() flips it left to right (along columns).	

In [22]:
#For a 1D array, you can reverse it using slicing or np.flip().

#1D Array Slicing:
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
reversed_arr_1d = arr_1d[::-1]
print(reversed_arr_1d)

[5 4 3 2 1]


In [24]:
#1D Array with np.flip():
reversed_arr_1d_flip = np.flip(arr_1d)
print(reversed_arr_1d_flip)

[5 4 3 2 1]


In [26]:
# Reversing a 2D Array
#For a 2D array, you can reverse along rows, columns, or both using slicing or np.flip().

#2D Array Definition:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


In [28]:
#Reverse the Entire 2D Array (Both Axes):

#Using np.flip() to reverse both rows and columns:
reversed_2d = np.flip(arr_2d)
print(reversed_2d)


[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [30]:
#Reverse the Rows (Axis 0):

#Using slicing or np.flip() with axis=0:
reversed_rows = arr_2d[::-1, :]
# or
reversed_rows_flip = np.flip(arr_2d, axis=0)
print(reversed_rows)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [32]:
#Reverse the Columns (Axis 1):

#Using slicing or np.flip() with axis=1:
reversed_cols = arr_2d[:, ::-1]
# or
reversed_cols_flip = np.flip(arr_2d, axis=1)
print(reversed_cols)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [34]:
#Use np.flipud() and np.fliplr() for Flipping Rows and Columns:

#Flip rows (upside down):
flipped_up_down = np.flipud(arr_2d)
print(flipped_up_down)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [36]:
#Flip columns (left to right):
flipped_left_right = np.fliplr(arr_2d)
print(flipped_left_right)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


##4  How can you determine the data type of elements in a NumPy array? Discuss the importance of data types 
in memory management and performance.



In [39]:
#In NumPy, you can easily determine the data type (also called dtype) of the elements in an array using the dtype attribute. Here's how:

In [41]:
import numpy as np

# Example array
arr = np.array([1, 2, 3, 4])

# Determine the data type of elements
print(arr.dtype)


int32


In [43]:
#Why Data Types Are Important in NumPy
#Data types (or dtypes) in NumPy define how much memory is allocated for each element and how the data is interpreted. Choosing the right data type is essential for both memory management and performance in numerical computing.

#Importance of Data Types in Memory Management
#Efficient Memory Usage:

#Different data types use different amounts of memory. For example, an int32 (32-bit integer) takes 4 bytes per element, while a float64 (64-bit floating point number) takes 8 bytes per element.
#Choosing a smaller data type for your array when you don't need larger precision saves memory.
#Example:
arr_int32 = np.array([1, 2, 3, 4], dtype='int32')
arr_float64 = np.array([1, 2, 3, 4], dtype='float64')

print(arr_int32.nbytes)  
print(arr_float64.nbytes) 


16
32


In [45]:
#Large Datasets:

#In data science and machine learning, you often work with very large datasets. Using efficient data types helps reduce memory usage, which is crucial for handling big datasets in-memory.
#For example, if you are working with categorical data that only has a few distinct values, you can use an int8 (1-byte integer) instead of int64, significantly reducing memory usage.

In [47]:
#Importance of Data Types in Performance
#Computation Speed:

#NumPy operations are optimized based on the data type of the array. Arrays with smaller or simpler data types (e.g., int32 vs. float64) can be processed faster because they require fewer CPU cycles.
#For example, when performing arithmetic operations on an array of int32, the processor can handle more elements in parallel compared to float64 elements, which are larger and may require more computational resources.

In [49]:
arr_small = np.ones(10**6, dtype='int32')
arr_large = np.ones(10**6, dtype='float64')

%timeit arr_small + 1 
%timeit arr_large + 1  


2.15 ms ± 229 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
2.51 ms ± 96.1 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [51]:
#Precision Control:

#Different data types offer different levels of precision. For example, using float32 instead of float64 saves memory but reduces precision, which can be critical in scientific computing where precision matters.
#For tasks like image processing or neural networks, lower precision (e.g., float16 or int8) is often sufficient and preferred for efficiency.
#Avoiding Overflow/Underflow:

#Choosing the right data type helps prevent issues like overflow (when a value exceeds the maximum limit of the data type) or underflow (when a value is too small to be represented). For instance, using int8 for a large integer dataset can lead to overflow errors, as it can only represent values from -128 to 127.

##5  Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In [54]:
#An ndarray (N-dimensional array) is the core data structure in NumPy, representing a multi-dimensional, homogeneous array of fixed-size items. It is optimized for fast numerical computations and memory efficiency. The term "N-dimensional" indicates that the array can have any number of dimensions (1D, 2D, 3D, etc.).

In [56]:
#Key Features of ndarray

#Homogeneous Data-	All elements in an ndarray must be of the same data type (e.g., all integers, floats, or booleans).
#Multidimensional-	ndarray can have multiple dimensions, from 1D arrays (vectors) to 2D arrays (matrices) and higher dimensions (tensors).
#Fixed Size-	Once created, the size of an ndarray is fixed, and elements cannot be added or removed dynamically like Python lists.
#Efficient Memory Layout-	Elements are stored in contiguous blocks of memory, making operations on large datasets highly efficient compared to Python lists.
#Vectorized Operations-	Supports fast element-wise operations without the need for explicit loops, enabling concise and high-performance numerical code.
#Shape and Size-	Each ndarray has a shape attribute (number of elements along each dimension) and a size attribute (total number of elements).
#Data Types (dtype)-	Arrays have a dtype that defines the data type of the elements (e.g., int32, float64), allowing for control over memory and precision.
#Broadcasting-	Supports broadcasting, allowing arrays of different shapes to be operated on together without reshaping them manually.
#Indexing and Slicing-	Provides powerful indexing and slicing capabilities for accessing and modifying elements, even across multiple dimensions.

In [58]:
import numpy as np

# Create a 2D ndarray (3x3 matrix)
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Check the key properties
print(arr.shape)  
print(arr.size)   
print(arr.dtype) 


(3, 3)
9
int32


In [60]:
#Differences Between ndarray and Standard Python Lists

#Homogeneity-	Elements must be of the same data type (e.g., all integers or floats).	Can store elements of different types (e.g., int, str, float).
#Performance-	Optimized for numerical operations, much faster due to contiguous memory layout and C-level optimizations.	Slower, especially for large datasets, since operations are done in pure Python.
#Memory Efficiency-	More memory-efficient because of fixed-size homogeneous data storage.	Uses more memory due to the flexible, variable-size nature of elements.
#Multi-dimensional-	Supports N-dimensional arrays, enabling handling of higher-dimensional data.	Python lists are inherently one-dimensional, but can nest lists to create higher dimensions (less efficient).
#Fixed Size-	Once created, the size of an ndarray is fixed (cannot append or remove elements dynamically).	Python lists are dynamic; you can add, remove, or insert elements at any time.
#Element-wise Operations-	Supports vectorized operations, allowing for element-wise mathematical operations without loops.	No direct support for element-wise operations; explicit loops are needed for operations on elements.
#Broadcasting-	Can perform operations between arrays of different shapes using broadcasting.	No native support for broadcasting; lists need to be reshaped manually.
#Indexing and Slicing-	More powerful and flexible indexing and slicing, supporting operations across multiple dimensions.	Less flexible, especially for multi-dimensional data.

In [62]:
#ndarray Element-wise Operation:
arr = np.array([1, 2, 3])
result = arr + 1  # Adds 1 to every element
print(result)  

[2 3 4]


In [64]:
#Python List (No Direct Element-wise Operation):
lst = [1, 2, 3]
result = [x + 1 for x in lst]  # Requires list comprehension or a loop
print(result)  

[2, 3, 4]


##6  Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations

In [67]:
#Performance Benefits of NumPy Arrays Over Python Lists for Large-Scale Numerical Operations
#NumPy arrays (ndarray) offer significant performance advantages over standard Python lists, particularly for large-scale numerical operations. These benefits come from several key optimizations in NumPy's design, including memory efficiency, support for vectorized operations, and lower-level implementation in C.

In [71]:
#1. Memory Efficiency
#Homogeneous Data Storage: NumPy arrays store data in a contiguous block of memory with a fixed data type, whereas Python lists are heterogeneous and store references to objects, which takes up more space.
#Fixed-Size Elements: Since all elements in a NumPy array are of the same data type, NumPy allocates memory more efficiently by avoiding the overhead associated with variable-sized Python objects.
import numpy as np
import sys

# NumPy array with 1 million integers
arr_np = np.arange(1000000)
print(arr_np.nbytes) 

# Python list with 1 million integers
arr_py = list(range(1000000))
print(sys.getsizeof(arr_py)) 


4000000
8000056


In [73]:
#2. Faster Execution (Vectorized Operations)
#NumPy operations are vectorized, meaning that they operate on entire arrays without the need for explicit Python loops. This makes NumPy much faster for large-scale numerical computations, as the operations are implemented in optimized C code and run at compiled speeds.

#Python Lists: Operations on Python lists often require looping through the list elements in Python, which is slow due to Python’s interpreted nature.
#NumPy Arrays: Operations on NumPy arrays are done element-wise in optimized C or Fortran code, which is far more efficient.

In [75]:
import numpy as np
import time

# NumPy array
arr_np = np.arange(1000000)

# Python list
arr_py = list(range(1000000))

# Add 1 to each element (element-wise addition)

# NumPy array operation (vectorized)
start_np = time.time()
arr_np += 1
end_np = time.time()

# Python list operation (using loop)
start_py = time.time()
arr_py = [x + 1 for x in arr_py]
end_py = time.time()

print("NumPy time:", end_np - start_np) 
print("Python list time:", end_py - start_py)


NumPy time: 0.0
Python list time: 0.10114073753356934


##7 . Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and 
output

In [78]:
#1. vstack() (Vertical Stacking)
#Functionality: vstack() stacks arrays along the vertical axis (row-wise), meaning that it adds arrays on top of each other.
#Shape Requirement: All arrays must have the same number of columns (i.e., the second dimension must match).

In [80]:
import numpy as np

# Creating two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Vertical stacking of 1D arrays
result = np.vstack((arr1, arr2))
print(result)


[[1 2 3]
 [4 5 6]]


In [82]:
#2D Example:
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])

# Vertical stacking of 2D arrays
result = np.vstack((arr3, arr4))
print(result)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [84]:
#2. hstack() (Horizontal Stacking)
#Functionality: hstack() stacks arrays along the horizontal axis (column-wise), meaning that it adds arrays side-by-side.
#Shape Requirement: All arrays must have the same number of rows (i.e., the first dimension must match).

In [86]:
import numpy as np

# Creating two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Horizontal stacking of 1D arrays
result = np.hstack((arr1, arr2))
print(result)


[1 2 3 4 5 6]


In [88]:
#2D Example:
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])

# Horizontal stacking of 2D arrays
result = np.hstack((arr3, arr4))
print(result)


[[1 2 5 6]
 [3 4 7 8]]


##8  Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various 
array dimensions.

In [91]:
#In NumPy, the functions fliplr() and flipud() are used to reverse the elements of an array along different axes. The key difference is the axis along which the reversal happens:

#fliplr(): Reverses the elements horizontally (i.e., left to right) along the columns of a 2D array.
#flipud(): Reverses the elements vertically (i.e., top to bottom) along the rows of a 2D array

In [93]:
#Example: fliplr()
import numpy as np

# Creating a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Flip the array horizontally (left to right)
result = np.fliplr(arr)
print(result)


[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [95]:
#Example: flipud()
import numpy as np

# Creating a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Flip the array vertically (top to bottom)
result = np.flipud(arr)
print(result)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [97]:
#Example with 3D Array:
import numpy as np

# Creating a 3D array (2 matrices of 3x3)
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],
                   
                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]]])

# Apply fliplr()
result_fliplr = np.fliplr(arr_3d)
print("fliplr() result:")
print(result_fliplr)

# Apply flipud()
result_flipud = np.flipud(arr_3d)
print("flipud() result:")
print(result_flipud)


fliplr() result:
[[[ 7  8  9]
  [ 4  5  6]
  [ 1  2  3]]

 [[16 17 18]
  [13 14 15]
  [10 11 12]]]
flipud() result:
[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]]


##9 Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

In [101]:
#The array_split() method in NumPy is used to split an array into multiple sub-arrays along a specified axis. It’s similar to the split() function but with an important difference: array_split() can handle uneven splits, whereas split() requires the array to be evenly divisible by the number of sub-arrays.

In [103]:
#Handling of Uneven Splits
#When the size of the array does not evenly divide by the number of sub-arrays, array_split() distributes the elements as evenly as possible. The first few sub-arrays will have one more element than the others.
#For example, if the array size is 10 and you want to split it into 3 sub-arrays, the first sub-array will have 4 elements, while the remaining two will have 3 elements each.

In [105]:
# Handling Uneven Splits
arr = np.arange(10)

# Split the array into 3 sub-arrays (uneven split)
result = np.array_split(arr, 3)
print(result)


[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [107]:
#Uneven Split Along Axis for 2D Arrays
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Split into 3 sub-arrays along columns (axis=1)
result = np.array_split(arr_2d, 3, axis=1)
print(result)


[array([[1, 2],
       [5, 6]]), array([[3],
       [7]]), array([[4],
       [8]])]


##10  Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array 
operations?

In [110]:
#Vectorization in NumPy
#Definition:
#Vectorization refers to the process of applying operations directly on whole arrays (vectors, matrices) without the need for explicit loops.
#It leverages low-level C and Fortran routines under the hood, allowing for fast execution and optimization.

In [112]:
# Adding two lists element-wise in pure Python
list1 = [1, 2, 3]
list2 = [4, 5, 6]
result = [list1[i] + list2[i] for i in range(len(list1))]
print(result)


[5, 7, 9]


In [114]:
#Broadcasting in NumPy
#Definition:
#Broadcasting is a technique that allows NumPy to perform element-wise operations on arrays of different shapes. It automatically expands smaller arrays to match the shape of larger arrays so that operations can proceed without errors.
#The smaller array is virtually "stretched" or "broadcast" across the larger array's shape, without making copies of the data.

In [116]:
import numpy as np

# 2D array
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

# 1D array
arr2 = np.array([1, 2, 3])

# Broadcasting arr2 to the shape of arr1 and adding them
result = arr1 + arr2
print(result)


[[2 4 6]
 [5 7 9]]


In [118]:
#Broadcasting with Scalar:
#When a scalar (single value) is used in operations with an array, broadcasting is applied to stretch the scalar to the shape of the array:
arr = np.array([1, 2, 3])

# Broadcasting scalar 5 across the array
result = arr + 5
print(result)


[6 7 8]


In [120]:
#Broadcasting Example for Arrays with Different Shapes:
#Consider a case where we add a 2D array to a 1D array with a shape that doesn't match exactly, but can still be broadcast:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([10, 20])

# Attempting to add arr1 and arr2
result = arr1 + arr2.reshape(-1, 1)
print(result)


[[11 12 13]
 [24 25 26]]
